# -*- coding: utf-8 -*-
# Non part of Odoo. See LICENSE file for full copyright and licensing details.

from odoo import fields, models, api
from odoo.exceptions import UserError

class stock_quant_move(models.TransientModel):
    """
    This wizard will confirm the all the selected draft invoices
    """

    _name = "stock.quant.move"
    _description = "move selected stock"

    name = fields.Char(required=False, translate=True)
    location_dest_id = fields.Many2one(
        'stock.location', 'Destination Location', index=True, ondelete='cascade', required=True,
         help="The new location where the goods need to go")
    move_confirm= fields.Char(required=False, translate=True)

    @api.multi

    def move_confirm(self):
	     context = dict(self._context or {})
        # active_ids = context.get('active_ids', []) or []

        # for record in self.env['account.invoice'].browse(active_ids):
        #    if record.state not in ('draft', 'proforma', 'proforma2'):
        #        raise UserError(_("Selected invoice(s) cannot be confirmed as they are not in 'Draft' or 'Pro-Forma' state."))
        #    record.action_invoice_open()
        return {'type': 'ir.actions.act_window_close'}